name: Build and deploy Python project to Azure Function App - blobuploadtest

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python version
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Deploy to Azure Functions
        uses: Azure/functions-action@v1
        with:
          app-name: 'blobuploadtest'  # Your function app name
          slot-name: 'Production'
          package: '.'                # Deploy from repo root
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_0D13EBAC3ABA490D909D56C221394FFC }}
